version: 'Compose-Spec'

services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: ip-192-168-0-12.ap-northeast-1.compute.internal
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      NEW_RELIC_LICENSE_KEY: "4d6b1fb1c2c1cf2a7c9be5d086e4f7297e0fNRAL"
      NEW_RELIC_APP_NAME: "isucon12-go"
      REDIS_ADDR: "redis:6379"
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
    init: true
